version: '3.4'
services:
  backend:
    build: .
    ports:
      - 8000:3000
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: admin
      MYSQL_USER: root
      MYSQL_PASSWORD: l4l4k3rs
      MYSQL_ROOT_PASSWORD: l4l4k3rs
    volumes:
      - .dbdata:/var/lib/mysql
    ports:
      - 33066:3306
